<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PartnerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $partners=[
            ['name' => 'Action Against Hunger (ACF)\منظمة العمل ضد الجوع'],
            ['name' => 'Aga Khan Foundation\الآغاخان'],
            ['name' => 'Ahali Aleppo\أهالي حلب'],
            ['name' => 'Ahel Alkher\أهل الخير'],
            ['name' => 'Ahl AlSham Initiative\مبادرة أهل الشام'],
            ['name' => 'Al Ahmadiya\الأحمدية الخيرية'],
            ['name' => 'Al Balad Al Amin\البلد الأمين'],
            ['name' => 'Al Barakeh NGO for Social Development\جمعية البركة للتنمية الاجتماعية'],
            ['name' => 'Al Batoul NGO\جمعية البتول'],
            ['name' => 'Al Birr and Al Ihsan Ras Al Ain\البر و الإحسان'],
            ['name' => 'Al Birr Association Deir Ezzor\جمعية البر - دير الزور'],
            ['name' => 'Al Birr Association Hama\جمعية البر - حماة'],
            ['name' => 'Al Birr Association Hasakeh\جمعية البر - الحسكة'],
            ['name' => 'Al Birr Association Homs\جمعية البر - حمص'],
            ['name' => 'Al Birr Association Idlib\جمعية البر - ادلب'],
            ['name' => 'Al Birr Association Qamishli\جمعية البر - القامشلى'],
            ['name' => 'Al Birr Association Raqqa\جمعية البر - الرقة'],
            ['name' => 'Al- Bostan Charity NGO\جمعية البستان'],
            ['name' => 'Al Ikhaa Syrian Family NGO\جمعية الإخاء'],
            ['name' => 'Al Kouds NGO\القدس'],
            ['name' => 'Al Maraa Al Zakia (Intelligent Woman) NGO\المرأة الذكية'],
            ['name' => 'Al Mouasat Islamic Charity NGO\المواساة الإسلامية الخيرية'],
            ['name' => 'Al Namaa\النماء'],
            ['name' => 'Al Rahma Assosiation in Qamishili\جمعية الرحمة في القامشلي'],
            ['name' => 'Al Rajaa\الرجاء'],
            ['name' => 'Al Tawahod association  \جمعية التوحد'],
            ['name' => 'Al Wasl Charity\جمعية الوصل'],
            ['name' => 'Al-Ammal NGO\الأمل'],
            ['name' => 'Al-Ansaar NGO\الأنصار'],
            ['name' => 'Al-Bashaeer NGO\البشائر'],
            ['name' => 'Al-Faihaa Charity NGO\الفيحاء الخيرية'],
            ['name' => 'Al-Golan NGO at Al-Hajar Alaswad\الجولان'],
            ['name' => 'Al-Ihsan Charity\الإحسان'],
            ['name' => 'Al-Ikhowa Charity\جمعية الأخوة'],
            ['name' => 'Al-Inmaa NGO\الإنماء'],
            ['name' => 'Al-Khabour NGO\الخابور'],
            ['name' => 'Almabarrat charity NGO for Golan people\المبرات الخيرية'],
            ['name' => 'AlMawada\جمعية المودة في الحسكة'],
            ['name' => 'Alnahda Alnisaye society\النهضة النسائية'],
            ['name' => 'Al-Nahda NGO\جمعية النهضة العربية للخدمات الاجتماعية'],
            ['name' => 'Al-Shaheed foundation\مؤسسة الشهيد'],
            ['name' => 'Al-Sham for Health Association\جمعية الشام الصحية'],
            ['name' => 'Al-Taalouf NGO\التآلف'],
            ['name' => 'AlTamayouz for Orphan Sponsorship/ Social care Association\مشروع التميز في كفالة اليتيم/الرعاية الاجتماعية'],
            ['name' => 'Al-Wasel NGO\الواصل'],
            ['name' => 'Al-Wifaq NGO ( Der-Atteia)\الوفاق'],
            ['name' => 'Al-Zahraa NGO\الزهراء'],
            ['name' => 'AMAAL Diabled NGO\آمال للمعاقين'],
            ['name' => 'Amis des Pauvres NGO\أصدقاء الفقير'],
            ['name' => 'Anis Saadeh\انيس سعادة'],
            ['name' => 'AOJP(Association of Jovenile Protection)\جمعية حماية الأحداث'],
            ['name' => 'Arab Women NGO in A-Hassakeh\المرأة العربية'],
            ['name' => 'Armenian Catholic Church\كنيسة الأرمن الكاثوليك'],
            ['name' => 'Arminian Charity\الجمعية الأرمنية'],
            ['name' => 'As Salamieyah Friends\أصدقاء السلمية'],
            ['name' => 'Asshiryan Charity at Tel Al-Ramel\جمعية السريان'],
            ['name' => 'Association of Juvenile Protection\جمعية رعاية الاحداث'],
            ['name' => 'Assyrian Charity\الجمعية الآشورية'],
            ['name' => 'Child Care NGO\جمعية العناية بالطفل'],
            ['name' => 'Child Protection NGO\حماية الطفل'],
            ['name' => 'Circassian charity association\الجمعية الشركسية الخيرية'],
            ['name' => 'Dar- Anisse llsaada\دار السعادة'],
            ['name' => 'Disabled people and their friends (DPAF)\جميعة ذوي الاحتياجات الخاصة واصدقائهم'],
            ['name' => 'DRC\المفوضية الدنماركية للاجئين'],
            ['name' => 'Dummar NGO\جمعية دمر'],
            ['name' => 'Education & Literacy NGO\جمعية التعليم و المعرفة'],
            ['name' => 'Education and Illiteracy Eradication Association (EIEA)\جمعية التعليم ومحو الأمية'],
            ['name' => 'Expatriates Friends Association in Maharda (E.F.A.M)\جمعية أصدقاء المغتربين في محردة'],
            ['name' => 'Family Organization NGO\جمعية الأسرة'],
            ['name' => 'For Aleppo NGO\من أجل حلب'],
            ['name' => 'Fouadi NGO\فؤادي - مؤسسة دعم التنمية المتكاملة'],
            ['name' => 'General Authority for Palestinian Arab Refugees (GAPAR)\الهيئة العامة للاجئين الفلسطينيين العرب'],
            ['name' => 'Greek Catholic Patriarchate\بطرياركية الروم الكاثوليك'],
            ['name' => 'Greek Orthodox Patriarchate\بطرياركية الروم الأورثودوكس'],
            ['name' => 'Hefz Alneeme charity NGO\جمعية حفظ النعمة'],
            ['name' => 'iecd\المعهد الأوروبي للتعاون و التطوير'],
            ['name' => 'Inaash Al Faqeer Charity in Al-Tal\جمعية إنعاش الفقير في التل'],
            ['name' => 'Insha`at NGO\جمعية الإنشاءات'],
            ['name' => 'International Medical Corps (IMC)\الهيئة الطبية الدولية'], 
            ['name' => 'Islamic Charity\الجمعيّة الخيريّة الإسلاميّة'],
            ['name' => 'Islamic Jaafari Charity NGO\الجمعية الجعفري الإسلامية'],
            ['name' => 'Kanawat Charity NGO\جمعية القنوات'],
            ['name' => 'Kareem Charity\جمعية كريم الخيرية'],
            ['name' => 'Khaled Ibn Al-Waleed\جمعية خالد ابن الوليد'],
            ['name' => 'Lamset Shifaa Charity NGO\جمعية لمسة شفاء'],
            ['name' => 'Ministry of Awqaf\وزارة الأوقاف'],
            ['name' => 'Ministry of Culture\وزارة الثقافة'],
            ['name' => 'Ministry of Education (MoE)\وزارة التربية'],
            ['name' => 'Ministry of Environment\وزارة البيئة'],
            ['name' => 'Ministry Of Health (MoH)\وزارة الصحة'],
            ['name' => 'Ministry of Higher Education (MoHE)\وزارة التعليم العالي'],
            ['name' => 'Ministry of Local Administration (MoLA)\وزارة الإدارة المحلية'],
            ['name' => 'Ministry of Social Affairs (MoSA)\وزارة الشؤون الاجتماعية'],
            ['name' => 'Ministry of Water Resources (MoWR)\وزارة الموارد المائية'],
            ['name' => 'Misyaf charity NGO\جمعية مصياف'],
            ['name' => 'NFRD (Nour Foundation)\مؤسسة النور'],
            ['name' => 'Oddod Al Fokaraa\جمعية عضد الفقراء'],
            ['name' => 'Orphan Girl NGO\جمعية الفتاة اليتيمة'],
            ['name' => 'Orthodox "Asdkaa Al-Fakeer" NGO\جمعية أصدقاء الفقير الأوثودوكسية'],
            ['name' => 'OXFAM\أوكسفام'],
            ['name' => 'Palestinian Charity NGO\الجمعية الفلسطينية الخيرية'],
            ['name' => 'Palestinian Red Crescent\الهلال الأحمر الفلسطيني'],
            ['name' => 'Poor raise charity NGO in Altal\جمعية النهوض بالفقراء الخيرية'],
            ['name' => 'Premiere Urgence (PU)\منظمة الإسعاف الأولي الدولية'],
            ['name' => 'Raise the health and social level NGO\جمعية النهوض بالوضع الصحي والاجتماعي'],
            ['name' => 'Relief and Development Center ( RDC) Syrian Catholic Archbishopric\مركز إغاثة و تنمية مطرانية الكاثوليك السورية'],
            ['name' => 'SAHPD\الجمعية السورية لتطوير برامج الصحة'],
            ['name' => 'Said Koureish Orphanage\ميتم سيد قريش'],
            ['name' => 'Saint Mansour charity NGO in Al-Hassakeh\جمعية القديس منصور'],
            ['name' => 'Sanabel Syria\جمعية سنابل سورية'],
            ['name' => 'Sandouk Alafieh NGO\صندوق العافية'],
            ['name' => 'SARC\الهلال الأحمر'],
            ['name' => 'Scouts\الكشافة'],
            ['name' => 'SEBC/ Mobaderoon\جمعية مبادرون'],
            ['name' => 'SECOURS ISLAMIQUE - FRANCE (SIF)\جمعية الإغاثة الفرنسية الإسلامية'],
            ['name' => 'Shabab El Kheir\شباب الخير'],
            ['name' => 'Shames Al-Golan NGO ( Hadar Village)\شمس الجولان'],
            ['name' => 'Small Roses Society\جمعية الورود الصغيرة'],
            ['name' => 'Social Care NGO\الرعاية الاجتماعية'],
            ['name' => 'SOS Children`s Village\قرى الأطفال'],
            ['name' => 'Syria Trust for Development\سيريا ترست'],
            ['name' => 'Syrian Association for children with special needs (SACSN)\الجمعية السورية للأطفال ذوي الاحتياجات الخاصة'],
            ['name' => 'Syrian Commission for family affairs\الهيئة السورية لشؤون الأسرة'],
            ['name' => 'Syrian Family NGO\الأسرة السورية'],
            ['name' => 'Syrian Family Planning Association (SFPA)\جمعية تنظيم الأسرة'],
            ['name' => 'Syrian Society for Social Development (SSSD)\الجمعية السورية للتنمبة الاجتماعية'],
            ['name' => 'Syrian Women NGO\جمعية المرأة السورية'],
            ['name' => 'Terre des Hommes Italia (TDH)\أرض الإنسان - إيطاليا'],
            ['name' => 'The Islamic Association Charity for Relief and Development – Aid (Aoun)\جمعية عون'],
            ['name' => 'UNICEF\يونيسف'],
            ['name' => 'Union Charity NGO\جمعية الإتحاد'],
            ['name' => 'UNRWA - United Nations Relief and Works Agency\وكالة الأمم المتحدة لإغاثة وتشغيل اللاجئين الفلسطينيين'],
            ['name' => 'Yadan Bi Yad all for special needs\يداً بيد - إحتياجات خاصة'],
            ['name' => 'Zahret Al-Madaeen NGO\زهرة المدائن'],
            ['name' => 'Al-Ihsan Association in Tal Hamis\جمعية الإحسان الخيرية تل حميس'],
            ['name' => 'Ministry of Information\وزارة الإعلام'],
            ['name' => 'Ministry of Interior\وزارة الداخلية'],
            ['name' => 'Armadilla Societa cooperativa sociale'],
            ['name' => 'Al Birr Association Daraa\جمعية البر - درعا'],
            ['name' => 'Al Ghadir Association\جمعية الغدير الخيرية'],
            ['name' => 'IOM - International Organization for Migration\المنظمة الدولية للهجرة'],
            ['name' => 'Awtar\أوتار'],
            ['name' => 'Child Rights NGO\جمعية حقوق الطفل'],
            ['name' => 'Syria Hope\سوريا الأمل'],
            ['name' => 'The Adventist Development and Relief Agency (ADRA)\وكالة الأدفنتست للإغاثة والتنمية الدولية'],
            ['name' => 'Childhood Protection Society\جمعية حماية الطفولة'],
            ['name' => 'Syria Hope NGO\جمعية سوريا الأمل'],
            ['name' => 'Souria Al Yamama Association\جمعية سوريا اليمامة'],
            ['name' => 'St. Ephrem Patriarchal Development Committee (EPDC)\هيئة مار أفرام السرياني البطريركية للتنمية'],
            ['name' => 'Gruppo Di Volontariato Civile (GVC)\مجموعة المتطوعين المدنيين'],
            ['name' => 'Health charity in Alqutaifah\جمعية الصحة الخيرية في القطيفة'],
            ['name' => 'Monastery Saint James the Mutilated (MSJM)\دير مار يعقوب المقطع'],
            ['name' => 'Health Charity in Al Quteifa\جمعية الصحة الخيرية في القطيفة'],
            ['name' => 'Ousrat Al-Ikhaa Al-Souria – Latakia\جمعية أسرة الإخاء السورية – اللاذقية'],
            ['name' => 'Mosaic human relief and development\جمعية موزاييك للإغاثة والتنمية الإنسانية'],
            ['name' => 'Amelioration of Sanitary and Social Level Society (ASSLS)\جمعية رفع المستوى الصحي والاجتماعي بحلب'],
            ['name' => 'Rebuild Syria Reconstruction Program NGO\جمعية برنامج إعادة إعمار سوريا'],
            ['name' => 'Church of Lady CCFP COMMITTEE\كنيسة السيدة هيئة كفام الاجتماعية'],
            ['name' => 'Basmet Amal\بصمة أمل'],
            ['name' => 'Bara`em Association for Children Care - Sweida\جمعية البراعم لرعاية الطفولة'],
            ['name' => 'Gruppo Di Volontariato Civile(GVC)\مجموعة المتطوعين المدنيين'],
            ['name' => 'ARCHBISHOPRIC OF SYRIAC CATHOLIC CENTER MAR ASSIA\مطرانية السريان الكاثوليك – مركز مار آسيا'],
            ['name' => 'Sham Alkher Association\جمعية شام الخير'],
            ['name' => 'Alqabas Charity Association\جمعية القبس الخيرية'],
            ['name' => 'COOPI\التعاون الدولي'],
            ['name' => 'BLIND NGO\جمعية الرعاية المكفوفين و ضعاف البصر'],
            ['name' => 'Arabian woman in DEZ\المرأة العربية دير الزور'],
            ['name' => 'Babel\بابل'],
            ['name' => 'Sanad Youth for Development\مؤسسة سند الشباب التنموية'],
            ['name' => 'International Labour Organization (ILO)\منظمة العمل الدولية'],
            ['name' => 'Mazeed NGO\جمعية مزيد الخيرية'],
            ['name' => 'Ghiras Association\جمعية غراس'],
            ['name' => 'Nebras Development Association\جمعية نبراس للتنمية'],
            ['name' => 'Wad Charity Association\جمعية ود الخيرية'],
            ['name' => 'Qameh Charity for Development/مؤسسة قمح للتنمية'],


        

            


        ];
        DB::table('partners')->insert($partners);
    }
}
